server:  
  ibof:
    ip: 127.0.0.1
    port: 18716
  bmc:
    ip: 192.168.0.3
    port: 443
  dagent:
    ip: 127.0.0.1
    port: 3000
ginfw:
  http: 
    port: 8080
    read_time_out: 60
    write_time_out: 60
  log:
    dir: log
logging:
  level: debug
  directory: log

 