@targetip=127.0.0.1:8080
@accept=application/json
@content_type=application/json

###
GET http://{{targetip}}/api/ibofos/v1/array
Content-Type: {{content_type}}
Accept: {{{accept}}}


###
GET http://{{targetip}}/api/ibofos/v1/system
Content-Type: {{content_type}}
Accept: {{{accept}}}

###
GET http://{{targetip}}/api/ibofos/v1/devices
Content-Type: {{content_type}}
Accept: {{{accept}}}

###
GET http://{{targetip}}/api/ibofos/v1/devices/all/scan
Content-Type: {{content_type}}
Accept: {{{accept}}}

###
GET http://{{targetip}}/api/ibofos/v1/devices/unvme-ns-0/smart
Content-Type: {{content_type}}
Accept: {{{accept}}}

###
GET http://{{targetip}}/api/ibofos/v1/volumes
Content-Type: {{content_type}}
Accept: {{{accept}}}

###
GET http://{{targetip}}/api/ibofos/v1/volumes?array=POSArray
Content-Type: {{content_type}}
Accept: {{{accept}}}

###
GET http://{{targetip}}/api/ibofos/v1/volumes/vol1?array=POSArray
Content-Type: {{content_type}}
Accept: {{{accept}}}

